#!/bin/bash
TARGET_SPOT="google.com"
LOG_FOLDER="Net_Health_Logs"
INTERVAL="5"
mkdir -p "$LOG_FOLDER"

CURRENT_SESSION_DATE=$(date +"%Y-%m-%d_%H-%M-%S")
FILE="$LOG_FOLDER/log_$CURRENT_SESSION_DATE.log"

touch "$FILE"

echo -e "\nNetwork monitoring HAS BEEN started at $(date +"%Y-%m-%d %H:%M:%S")" >> "$FILE"
echo -e "\nNetwork monitoring HAS BEEN started at $(date +"%Y-%m-%d %H:%M:%S")"
on_exit() {
    echo -e "\nNetwork monitoring HAS BEEN stopped at $(date +"%Y-%m-%d %H:%M:%S")" >> $FILE
    echo -e "\nNetwork monitoring HAS BEEN stopped at $(date +"%Y-%m-%d %H:%M:%S")"
    exit 0
}

trap on_exit SIGINT

while true; do
    echo "**************************************************" >> $FILE
    echo "time during ping: $(date +"%Y-%m-%d %H:%M:%S")" >> $FILE
    ping -c 3 -W 2 "$TARGET_SPOT" >> "$FILE" 2>&1

    if [[ $? -eq 0 ]]; then
        echo "Reachable" >> "$FILE"
    else
        echo "Unreachable" >> "$FILE"
    fi
    sleep "$INTERVAL"
done